[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://al-in.fr"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
    Access-Control-Allow-Credentials = "true"
    Referrer-Policy = "strict-origin-when-cross-origin"